### ISSUE TITLE
Script Execution Flow Documentation

### ISSUE THREAD

**Issue by luke-beep** [prolix-oc/Refyne#7]
## Description

This issue is to track the creation of a new documentation that explains the execution flow of the `Refyne.ps1` script. This will help other developers & users understand what's going on when the script is executed.

## Tasks

- [x] Understand the current execution flow of `Refyne.ps1`
- [x] Write a step-by-step guide that explains the execution flow
- [x] Include examples and/or diagrams where necessary
- [x] Review the guide for clarity and accuracy
- [x] Add the guide to the repository's documentation

## Execution Flow

The ongoing development can be viewed [here](https://github.com/prolix-oc/Refyne/blob/master/docs/Refyne_Execution_Flow.md)
